### ISSUE TITLE
req-url-extra-0.1.0.0 build failure with req-2.0.0

### ISSUE THREAD

**Issue by DanBurton** [rcook/req-url-extra#1]
Use `defaultHttpConfig` instead of `def` to fix this build failure.

(see the req changelog: https://hackage.haskell.org/package/req-2.0.0/changelog)

```
Building executable 'sample' for req-url-extra-0.1.0.0..
[1 of 1] Compiling Main             ( sample/Main.hs, dist/build/sample/sample-tmp/Main.o )

sample/Main.hs:14:17: error:
    • No instance for (Data.Default.Class.Default
                         Network.HTTP.Req.HttpConfig)
        arising from a use of ‘def’
    • In the first argument of ‘runReq’, namely ‘def’
      In the expression: runReq def
      In a stmt of a 'do' block:
        v <- runReq def $ req GET url NoReqBody jsonResponse opts
   |
14 |     v <- runReq def $ req GET url NoReqBody jsonResponse opts
   |                 ^^^
```

**Comment by rcook** [comment]
@DanBurton : I've fixed this issue and published a new version of the package: http://hackage.haskell.org/package/req-url-extra-0.1.1.0. Are there any other steps I need to take to re-enable this in Stackage?

**Comment by DanBurton** [comment]
The PR you opened on stackage was all that was necessary; looks like it built correctly and will be published in the next nightly.
